version: '3'

services:
  postgres_database:
    image: postgres
    container_name: pg-databases
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_dev  

    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: on-failure

volumes:
  database-volume:
